In [1]:
import polars as pl
import pandas as pd
import duckdb
import matplotlib.pyplot as plt

## 1. Yellow Taxi in 2009

In [2]:
query_yellow_2009 = """
WITH CTE_2009 AS (
    SELECT 
        CAST(Trip_Pickup_DateTime AS TIMESTAMP) AS pick_up_time,
        CAST(Trip_Dropoff_DateTime AS TIMESTAMP) AS drop_off_time,
        CAST(Passenger_Count AS INTEGER) AS passenger_count,
        CAST(Trip_Distance AS INTEGER) AS trip_distance,
        Payment_Type AS payment_type,
        CAST(Total_Amt AS FLOAT)   AS total_amount,
        Tip_Amt AS tip_amount,
        CAST(Tip_Amt AS FLOAT)   AS tip_amount,
        CAST( CASE Payment_Type
            WHEN  'Credit' THEN 1
            WHEN  'CREDIT' THEN 1
            ELSE 2
        END AS INTEGER) AS payment_category,
        CAST( CASE Tip_Amt
            WHEN  0.0 THEN 1
            ELSE 0
        END AS INTEGER) AS tip_category
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2009/yellow_taxi_2009/yellow_tripdata_*.parquet'
    WHERE Trip_Pickup_DateTime IS NOT NULL
        AND Trip_Dropoff_DateTime IS NOT NULL
        AND Passenger_Count >= 0
        AND Trip_Distance >= 0 
        AND Trip_Distance <= 50
        AND Payment_Type IS NOT NULL
        AND Total_Amt >= 0
        AND Tip_Amt >= 0
        AND Trip_Pickup_DateTime >= '2009-01-01' 
        AND Trip_Pickup_DateTime < '2010-01-01'
), CTE_duration_2009 AS (
    SELECT
        pick_up_time,
        drop_off_time,
        passenger_count,
        trip_distance,
        total_amount,
        payment_category,
        tip_category,
        DATE_DIFF('day', pick_up_time, drop_off_time) AS duration_days,
        EPOCH(drop_off_time - pick_up_time) AS duration_seconds
    FROM CTE_2009
    WHERE payment_category = 1
)

SELECT 
    passenger_count,
    trip_distance,
    total_amount,
    CAST(duration_seconds AS FLOAT)   AS duration_seconds,
    tip_category
FROM CTE_duration_2009
WHERE duration_days = 0
"""

con = duckdb.connect()
df_yellow_2009 = con.execute(query_yellow_2009).fetchdf()
df_yellow_2009.head()

,passenger_count,trip_distance,total_amount,duration_seconds,tip_category
0,3,5,14.600000,420.0,0
1,5,10,28.440001,840.0,0
2,1,5,18.450001,1262.0,0
3,1,0,6.700000,585.0,0
4,1,2,10.000000,679.0,0

In [3]:
df_yellow_2009.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44389926 entries, 0 to 44389925
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   passenger_count   int32
 1   trip_distance     int32
 2   total_amount      float32
 3   duration_seconds  float32
 4   tip_category      int32
dtypes: float32(2), int32(3)
memory usage: 846.7 MB

In [4]:
df_yellow_2009['tip_category'].value_counts()

tip_category
0    43056871
1     1333055
Name: count, dtype: int64

In [5]:
df_yellow_2009.isnull().sum()

passenger_count     0
trip_distance       0
total_amount        0
duration_seconds    0
tip_category        0
dtype: int64

In [6]:
len(df_yellow_2009)

44389926

## 2. Yellow Taxi in 2010

In [7]:
query_yellow_2010 = """
WITH CTE_2010 AS (
    SELECT 
        CAST(pickup_datetime AS TIMESTAMP) AS pick_up_time,
        CAST(dropoff_datetime AS TIMESTAMP) AS drop_off_time,
        CAST(passenger_count AS INTEGER) AS passenger_count,
        CAST(total_amount AS FLOAT)   AS total_amount,
        CAST(trip_distance AS FLOAT)   AS trip_distance,
        payment_type,
        tip_amount,
        CAST( CASE payment_type
            WHEN  'Cre' THEN 1
            WHEN  'CRE' THEN 1
            ELSE 2
        END AS INTEGER) AS payment_category,
        CAST( CASE tip_amount
            WHEN  0.0 THEN 1
            ELSE 0
        END AS INTEGER) AS tip_category
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2010/yellow_taxi_2010/yellow_tripdata_*.parquet'
    WHERE pickup_datetime IS NOT NULL
        AND dropoff_datetime  IS NOT NULL
        AND passenger_count >= 0
        AND trip_distance >= 0
        AND trip_distance <= 50
        AND payment_type IS NOT NULL
        AND total_amount >= 0
        AND tip_amount >= 0 
        AND pickup_datetime >= '2010-01-01' 
        AND pickup_datetime < '2011-01-01'
), CTE_duration_2010 AS (
    SELECT
        pick_up_time,
        drop_off_time,
        passenger_count,
        trip_distance,
        total_amount,
        payment_category,
        tip_category,
        DATE_DIFF('day', pick_up_time, drop_off_time) AS duration_days,
        EPOCH(drop_off_time - pick_up_time) AS duration_seconds
    FROM CTE_2010
    WHERE payment_category = 1
)

SELECT 
    passenger_count,
    trip_distance,
    total_amount,
    CAST(duration_seconds AS FLOAT)   AS duration_seconds,
    tip_category
FROM CTE_duration_2010
WHERE duration_days = 0
"""

con = duckdb.connect()
df_yellow_2010 = con.execute(query_yellow_2010).fetchdf()
df_yellow_2010.head()

,passenger_count,trip_distance,total_amount,duration_seconds,tip_category
0,1,0.60,6.67,413.0,0
1,1,3.30,12.00,866.0,0
2,1,1.42,12.00,840.0,0
3,1,0.84,10.20,480.0,0
4,1,2.00,10.50,893.0,0

In [8]:
df_yellow_2010['passenger_count'].value_counts()

passenger_count
1    22196449
2     4385618
5     2228270
3     1111395
4      436353
6      106201
0         422
9           2
7           1
Name: count, dtype: int64

In [9]:
df_yellow_2010['tip_category'].value_counts()

tip_category
0    29646184
1      818527
Name: count, dtype: int64

In [10]:
df_yellow_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30464711 entries, 0 to 30464710
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   passenger_count   int32
 1   trip_distance     float32
 2   total_amount      float32
 3   duration_seconds  float32
 4   tip_category      int32
dtypes: float32(3), int32(2)
memory usage: 581.1 MB

In [11]:
df_yellow_2010.isnull().sum()

passenger_count     0
trip_distance       0
total_amount        0
duration_seconds    0
tip_category        0
dtype: int64

In [12]:
len(df_yellow_2010)

30464711

## 3. Yellow Taxi in Between 2011 and 2023

In [14]:
query_yellow_2011_2023 = """
WITH CTE_2011_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        CAST(passenger_count AS INTEGER) AS passenger_count,
        CAST(total_amount AS FLOAT)   AS total_amount,
        CAST(trip_distance AS FLOAT)   AS trip_distance,
        CAST(payment_type AS INTEGER) AS payment_category,
        tip_amount,
        CAST( CASE tip_amount
            WHEN  0.0 THEN 1
            ELSE 0
        END AS INTEGER) AS tip_category
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/*/yellow_taxi/yellow_tripdata_*.parquet'
    WHERE tpep_pickup_datetime IS NOT NULL
        AND tpep_dropoff_datetime  IS NOT NULL
        AND passenger_count IS NOT NULL
        AND trip_distance >= 0
        AND trip_distance <= 50
        AND payment_type IS NOT NULL
        AND total_amount >= 0
        AND tip_amount >= 0
        AND tpep_pickup_datetime >= '2011-01-01' 
        AND tpep_pickup_datetime < '2023-10-01'
), CTE_duration_2011_2023 AS (
    SELECT
        pick_up_time,
        drop_off_time,
        passenger_count,
        trip_distance,
        total_amount,
        payment_category,
        tip_category,
        DATE_DIFF('day', pick_up_time, drop_off_time) AS duration_days,
        EPOCH(drop_off_time - pick_up_time) AS duration_seconds
    FROM CTE_2011_2023
    WHERE payment_category = 1
)

SELECT 
    passenger_count,
    trip_distance,
    total_amount,
    CAST(duration_seconds AS FLOAT)   AS duration_seconds,
    tip_category
FROM CTE_duration_2011_2023
WHERE duration_days = 0
LIMIT 5
"""

con = duckdb.connect()
df_yellow_2011_2023 = con.execute(query_yellow_2011_2023).fetchdf()
df_yellow_2011_2023.head()

,passenger_count,trip_distance,total_amount,duration_seconds,tip_category
0,4,0.0,4.18,120.0,0
1,4,0.0,6.94,540.0,0
2,4,0.0,5.01,120.0,0
3,5,0.0,3.90,120.0,1
4,5,0.0,3.61,0.0,0

## 4. Green Taxi from 2009 until 2023

In [ ]:
len(df_yellow_2011_2023)

shape: (3, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2011-01-0 ┆ 2011-01-0 ┆ 4         ┆ … ┆ 0.0       ┆ 4.18      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:10:00  ┆ 00:12:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2011-01-0 ┆ 2011-01-0 ┆ 4         ┆ … ┆ 0.0       ┆ 6.94      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:04:00  ┆ 00:13:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2011-01-0 ┆ 2011-01-0 ┆ 4         ┆ … ┆ 0.0       ┆ 5.01      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:14:00  ┆ 00:16:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

rate_code
1    14863778
Name: count, dtype: int64

In [9]:
yellow_2010 = pd.read_parquet(r"C:\Users\ekadw\Documents\DATA\NY_Taxi\2010\yellow_taxi_2010\yellow_tripdata_2010-01.parquet")
yellow_2010.head()

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,rate_code,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,surcharge,mta_tax,tip_amount,tolls_amount,total_amount
0,VTS,2010-01-26 07:41:00,2010-01-26 07:45:00,1,0.75,-73.956778,40.767750,1,None,-73.965957,40.765232,CAS,4.5,0.0,0.5,0.00,0.0,5.00
1,DDS,2010-01-30 23:31:00,2010-01-30 23:46:12,1,5.90,-73.996118,40.763932,1,None,-73.981512,40.741193,CAS,15.3,0.5,0.5,0.00,0.0,16.30
2,DDS,2010-01-18 20:22:20,2010-01-18 20:38:12,1,4.00,-73.979673,40.783790,1,None,-73.917852,40.878560,CAS,11.7,0.5,0.5,0.00,0.0,12.70
3,VTS,2010-01-09 01:18:00,2010-01-09 01:35:00,2,4.70,-73.977922,40.763997,1,None,-73.923908,40.759725,CAS,13.3,0.5,0.5,0.00,0.0,14.30
4,CMT,2010-01-18 19:10:14,2010-01-18 19:17:07,1,0.60,-73.990924,40.734682,1,0,-73.995511,40.739088,Cre,5.3,0.0,0.5,0.87,0.0,6.67

In [10]:
yellow_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14863778 entries, 0 to 14863777
Data columns (total 18 columns):
 #   Column              Dtype
---  ------              -----
 0   vendor_id           object
 1   pickup_datetime     object
 2   dropoff_datetime    object
 3   passenger_count     int64
 4   trip_distance       float64
 5   pickup_longitude    float64
 6   pickup_latitude     float64
 7   rate_code           object
 8   store_and_fwd_flag  object
 9   dropoff_longitude   float64
 10  dropoff_latitude    float64
 11  payment_type        object
 12  fare_amount         float64
 13  surcharge           float64
 14  mta_tax             float64
 15  tip_amount          float64
 16  tolls_amount        float64
 17  total_amount        float64
dtypes: float64(11), int64(1), object(6)
memory usage: 2.0+ GB

In [11]:
yellow_2010['payment_type'].value_counts()

payment_type
CAS    5621301
Cre    4532676
Cas    4424339
CRE     242607
No       35258
Dis       7597
Name: count, dtype: int64

In [20]:
yellow_2009 = pd.read_parquet(r"C:\Users\ekadw\Documents\DATA\NY_Taxi\2009\yellow_taxi_2009\yellow_tripdata_2009-01.parquet")
yellow_2009.head()

,vendor_name,Trip_Pickup_DateTime,Trip_Dropoff_DateTime,Passenger_Count,Trip_Distance,Start_Lon,Start_Lat,Rate_Code,store_and_forward,End_Lon,End_Lat,Payment_Type,Fare_Amt,surcharge,mta_tax,Tip_Amt,Tolls_Amt,Total_Amt
0,VTS,2009-01-04 02:52:00,2009-01-04 03:02:00,1,2.63,-73.991957,40.721567,NaN,NaN,-73.993803,40.695922,CASH,8.9,0.5,NaN,0.00,0.0,9.40
1,VTS,2009-01-04 03:31:00,2009-01-04 03:38:00,3,4.55,-73.982102,40.736290,NaN,NaN,-73.955850,40.768030,Credit,12.1,0.5,NaN,2.00,0.0,14.60
2,VTS,2009-01-03 15:43:00,2009-01-03 15:57:00,5,10.35,-74.002587,40.739748,NaN,NaN,-73.869983,40.770225,Credit,23.7,0.0,NaN,4.74,0.0,28.44
3,DDS,2009-01-01 20:52:58,2009-01-01 21:14:00,1,5.00,-73.974267,40.790955,NaN,NaN,-73.996558,40.731849,CREDIT,14.9,0.5,NaN,3.05,0.0,18.45
4,DDS,2009-01-24 16:18:23,2009-01-24 16:24:56,1,0.40,-74.001580,40.719382,NaN,NaN,-74.008378,40.720350,CASH,3.7,0.0,NaN,0.00,0.0,3.70

In [ ]:
query_classification = """
WITH CTE_yellow_2009 AS (
    SELECT 
        Trip_Pickup_DateTime AS pick_up_time,
        Trip_Dropoff_DateTime AS drop_off_time,
        Passenger_Count AS passenger_count,
        Trip_Distance AS trip_distance,
        Payment_Type AS payment_type,
        Total_Amt AS total_amount,
        Tip_Amt AS tip_amount,
        CASE Payment_Type
            WHEN  'Credit' THEN 1
            WHEN  'CREDIT' THEN 1
            ELSE 2
        END AS Payment_Category
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2009/yellow_taxi_2009/yellow_tripdata_*.parquet'
    WHERE Trip_Pickup_DateTime IS NOT NULL
        AND Trip_Dropoff_DateTime IS NOT NULL
        AND Passenger_Count >= 0
        AND Trip_Distance >= 0
        AND Trip_Distance <= 50
        AND Payment_Type IS NOT NULL
        AND Total_Amt >= 0
        AND Tip_Amt IS >= 0
        AND Trip_Pickup_DateTime >= '2009-01-01' 
        AND Trip_Pickup_DateTime < '2010-10-01'
), CTE_yellow_2010 AS (
    SELECT 
        pickup_datetime AS pick_up_time,
        dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2010/yellow_taxi_2010/yellow_tripdata_*.parquet'
    WHERE pickup_datetime IS NOT NULL
        AND dropoff_datetime IS NOT NULL
        AND passenger_count IS NOT NULL
        AND trip_distance IS NOT NULL
        AND payment_type IS NOT NULL
        AND total_amount IS NOT NULL
        AND tip_amount IS NOT NULL
        AND pickup_datetime >= '2010-01-01' 
        AND pickup_datetime < '2011-01-01'
), CTE_yellow_2011_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/*/yellow_taxi/yellow_tripdata_*.parquet'
    WHERE tpep_pickup_datetime IS NOT NULL
        AND tpep_dropoff_datetime IS NOT NULL
        AND passenger_count IS NOT NULL
        AND trip_distance IS NOT NULL
        AND payment_type IS NOT NULL
        AND total_amount IS NOT NULL
        AND tip_amount IS NOT NULL
        AND tpep_pickup_datetime >= '2011-01-01' 
        AND tpep_dropoff_datetime < '2023-10-01'
), CTE_union_yellow_2009_2023 AS (
    SELECT * FROM CTE_yellow_2009
    UNION ALL
    SELECT * FROM CTE_yellow_2010
    UNION ALL
    SELECT * FROM CTE_yellow_2011_2023
), CTE_count_trip AS (
    SELECT
        DATE(pick_up_time) AS pick_up_date
    FROM CTE_union_yellow_2009_2023
)

SELECT 
    pick_up_date AS day_of_trip,
    COUNT(*) AS total_trip
FROM CTE_count_trip
GROUP BY pick_up_date
ORDER BY pick_up_date 
"""

con = duckdb.connect()
df_classification = con.execute(query_classification).fetchdf()
df_classification.head()

In [5]:
query_yellow_2009 = """
WITH CTE_yellow_2009 AS (
    SELECT 
        Trip_Pickup_DateTime AS pick_up_time,
        Trip_Dropoff_DateTime AS drop_off_time,
        Passenger_Count AS passenger_count,
        Trip_Distance AS trip_distance,
        Payment_Type AS payment_type,
        Total_Amt AS total_amount,
        Tip_Amt AS tip_amount,
        CASE Payment_Type
            WHEN  'Credit' THEN 1
            WHEN  'CREDIT' THEN 1
            ELSE 2
        END AS payment_category
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2009/yellow_taxi_2009/yellow_tripdata_*.parquet'
    WHERE Trip_Pickup_DateTime IS NOT NULL
        AND Trip_Dropoff_DateTime IS NOT NULL
        AND (Passenger_Count >= 0)
        AND (Trip_Distance >= 0)
        AND (Trip_Distance <= 50)
        AND Payment_Type IS NOT NULL
        AND (Total_Amt >= 0)
        AND (Tip_Amt IS >= 0)
        AND (Trip_Pickup_DateTime >= '2009-01-01') 
        AND (Trip_Pickup_DateTime < '2010-10-01')
)

SELECT 
    passenger_count,
    trip_distance,
    total_amount
FROM CTE_yellow_2009
"""

con = duckdb.connect()
df_yellow_2009 = con.execute(query_yellow_2009).fetchdf()
df_yellow_2009.head()

ParserException: Parser Error: syntax error at or near ">="

In [ ]:
query_classification = """
WITH CTE_yellow_2009 AS (
    SELECT 
        Trip_Pickup_DateTime AS pick_up_time,
        Trip_Dropoff_DateTime AS drop_off_time,
        Passenger_Count AS passenger_count,
        Trip_Distance AS trip_distance,
        Payment_Type AS payment_type,
        Total_Amt AS total_amount,
        Tip_Amt AS tip_amount,
        CASE Payment_Type
            WHEN  'Credit' THEN 1
            WHEN  'CREDIT' THEN 1
            ELSE 2
        END AS Payment_Category
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2009/yellow_taxi_2009/yellow_tripdata_*.parquet'
    WHERE Trip_Pickup_DateTime IS NOT NULL
        AND Trip_Dropoff_DateTime IS NOT NULL
        AND Passenger_Count >= 0
        AND Trip_Distance >= 0
        AND Trip_Distance <= 50
        AND Payment_Type IS NOT NULL
        AND Total_Amt >= 0
        AND Tip_Amt IS >= 0
        AND Trip_Pickup_DateTime >= '2009-01-01' 
        AND Trip_Pickup_DateTime < '2010-10-01'
), CTE_yellow_2010 AS (
    SELECT 
        pickup_datetime AS pick_up_time,
        dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2010/yellow_taxi_2010/yellow_tripdata_*.parquet'
    WHERE pickup_datetime IS NOT NULL
        AND dropoff_datetime IS NOT NULL
        AND passenger_count IS NOT NULL
        AND trip_distance IS NOT NULL
        AND payment_type IS NOT NULL
        AND total_amount IS NOT NULL
        AND tip_amount IS NOT NULL
        AND pickup_datetime >= '2010-01-01' 
        AND pickup_datetime < '2011-01-01'
), CTE_yellow_2011_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/*/yellow_taxi/yellow_tripdata_*.parquet'
    WHERE tpep_pickup_datetime IS NOT NULL
        AND tpep_dropoff_datetime IS NOT NULL
        AND passenger_count IS NOT NULL
        AND trip_distance IS NOT NULL
        AND payment_type IS NOT NULL
        AND total_amount IS NOT NULL
        AND tip_amount IS NOT NULL
        AND tpep_pickup_datetime >= '2011-01-01' 
        AND tpep_dropoff_datetime < '2023-10-01'
), CTE_union_yellow_2009_2023 AS (
    SELECT * FROM CTE_yellow_2009
    UNION ALL
    SELECT * FROM CTE_yellow_2010
    UNION ALL
    SELECT * FROM CTE_yellow_2011_2023
), CTE_count_trip AS (
    SELECT
        DATE(pick_up_time) AS pick_up_date
    FROM CTE_union_yellow_2009_2023
)

SELECT 
    pick_up_date AS day_of_trip,
    COUNT(*) AS total_trip
FROM CTE_count_trip
GROUP BY pick_up_date
ORDER BY pick_up_date 
"""

con = duckdb.connect()
df_classification = con.execute(query_classification).fetchdf()
df_classification.head()