In [1]:
import polars as pl
import duckdb

In [19]:
yellow_2023 = pl.read_parquet(r"C:\Users\ekadw\Documents\DATA\NY_Taxi\2022\yellow_taxi\yellow_tripdata_2022-01.parquet")
yellow_2023.head()

shape: (5, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 2.0       ┆ … ┆ 0.3       ┆ 21.95     ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:35:40  ┆ 00:53:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 13.3      ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:33:43  ┆ 00:42:07  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 10.56     ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:53:21  ┆ 01:02:19  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 11.8      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:25:21  ┆ 00:35:23  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 30.3      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:36:48  ┆ 01:14:20  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
query = """
WITH CTE_jan_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2023/yellow_taxi/yellow_tripdata_2023-01.parquet'
)

SELECT 
    *
FROM CTE_jan_2023
"""

con = duckdb.connect()
df = con.execute(query).fetchdf()
df.head()

,pick_up_time,drop_off_time,passenger_count,trip_distance,payment_type,total_amount,tip_amount
0,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,2,14.30,0.00
1,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1,16.90,4.00
2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1,34.90,15.00
3,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1,20.85,0.00
4,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1,19.68,3.28

In [26]:
query_count = """
WITH CTE_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2023/yellow_taxi/yellow_tripdata_*.parquet'
), CTE_count_trip AS (
    SELECT
        DATE(pick_up_time) AS pick_up_date
    FROM CTE_2023
)

SELECT 
    pick_up_date,
    COUNT(*)
FROM CTE_count_trip
GROUP BY pick_up_date
ORDER BY pick_up_date DESC
"""

con = duckdb.connect()
df = con.execute(query_count).fetchdf()
df.head()

  pick_up_date  count_star()
0   2023-10-16             2
1   2023-10-01             8
2   2023-09-30        113243
3   2023-09-29        105091
4   2023-09-28        127429

In [22]:
df.head(50)

   pick_up_date  count_star()
0    2023-04-18             1
1    2023-01-01             5
2    2022-12-31         85075
3    2022-12-30         92429
4    2022-12-29         93498
5    2022-12-28         89065
6    2022-12-27         86290
7    2022-12-26         67459
8    2022-12-25         50109
9    2022-12-24         75519
10   2022-12-23         95028
11   2022-12-22        102850
12   2022-12-21        113560
13   2022-12-20        116021
14   2022-12-19        112460
15   2022-12-18        102878
16   2022-12-17        125382
17   2022-12-16        127755
18   2022-12-15        131175
19   2022-12-14        129324
20   2022-12-13        124239
21   2022-12-12        112374
22   2022-12-11        107756
23   2022-12-10        129278
24   2022-12-09        135397
25   2022-12-08        133862
26   2022-12-07        125589
27   2022-12-06        120179
28   2022-12-05        113626
29   2022-12-04        111619
30   2022-12-03        129172
31   2022-12-02        129951
32   2022-12-01        130641
33   2022-11-30        117718
34   2022-11-29        119372
35   2022-11-28        106488
36   2022-11-27         90529
37   2022-11-26         99513
38   2022-11-25         86607
39   2022-11-24         69663
40   2022-11-23        105640
41   2022-11-22        114546
42   2022-11-21        108526
43   2022-11-20         81125
44   2022-11-19         94932
45   2022-11-18         95454
46   2022-11-17         95344
47   2022-11-16         92660
48   2022-11-15         90728
49   2022-11-14         82278

In [39]:
query_count = """
WITH CTE_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2010/yellow_taxi/yellow_tripdata_*.parquet'
), CTE_count_trip AS (
    SELECT
        DATE(pick_up_time) AS pick_up_date
    FROM CTE_2023
)

SELECT 
    COUNT(*)
FROM CTE_count_trip
"""

con = duckdb.connect()
df = con.execute(query_count).fetchdf()
df.head()

BinderException: Binder Error: Referenced column "tpep_pickup_datetime" not found in FROM clause!
Candidate bindings: "pickup_datetime", "pickup_latitude", "rate_code", "pickup_longitude", "trip_distance"

LINE 4:         tpep_pickup_datetime AS pick_up_time,
                ^