In [1]:
import polars as pl
import duckdb

In [19]:
yellow_2023 = pl.read_parquet(r"C:\Users\ekadw\Documents\DATA\NY_Taxi\2022\yellow_taxi\yellow_tripdata_2022-01.parquet")
yellow_2023.head()

shape: (5, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 2.0       ┆ … ┆ 0.3       ┆ 21.95     ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:35:40  ┆ 00:53:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 13.3      ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:33:43  ┆ 00:42:07  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 10.56     ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:53:21  ┆ 01:02:19  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 11.8      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:25:21  ┆ 00:35:23  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 30.3      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:36:48  ┆ 01:14:20  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
query = """
WITH CTE_jan_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2023/yellow_taxi/yellow_tripdata_2023-01.parquet'
)

SELECT 
    *
FROM CTE_jan_2023
"""

con = duckdb.connect()
df = con.execute(query).fetchdf()
df.head()

,pick_up_time,drop_off_time,passenger_count,trip_distance,payment_type,total_amount,tip_amount
0,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,2,14.30,0.00
1,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1,16.90,4.00
2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1,34.90,15.00
3,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1,20.85,0.00
4,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1,19.68,3.28

In [44]:
query_count = """
WITH CTE_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2023/yellow_taxi/yellow_tripdata_*.parquet'
    WHERE tpep_pickup_datetime IS NOT NULL
        AND tpep_dropoff_datetime IS NOT NULL
        AND passenger_count IS NOT NULL
        AND trip_distance IS NOT NULL
        AND payment_type IS NOT NULL
        AND total_amount IS NOT NULL
        AND tip_amount IS NOT NULL
), CTE_count_trip AS (
    SELECT
        DATE(pick_up_time) AS pick_up_date
    FROM CTE_2023
)

SELECT 
    pick_up_date,
    COUNT(*)
FROM CTE_count_trip
WHERE pick_up_date >= '2009-01-01' AND pick_up_date < '2023-10-01'
GROUP BY pick_up_date
ORDER BY pick_up_date DESC
"""

con = duckdb.connect()
df = con.execute(query_count).fetchdf()
df.head()

  pick_up_date  count_star()
0   2023-09-30        108446
1   2023-09-29         95916
2   2023-09-28        121503
3   2023-09-27        114350
4   2023-09-26        107736

In [46]:
df.head(50)

   pick_up_date  count_star()
0    2023-09-30        108446
1    2023-09-29         95916
2    2023-09-28        121503
3    2023-09-27        114350
4    2023-09-26        107736
5    2023-09-25         87644
6    2023-09-24           125
7    2023-09-23            18
8    2023-09-22            20
9    2023-09-21         37282
10   2023-09-20        104203
11   2023-09-19        100220
12   2023-09-18         91317
13   2023-09-17         89455
14   2023-09-16        106004
15   2023-09-15        111937
16   2023-09-14        120918
17   2023-09-13        114452
18   2023-09-12        114358
19   2023-09-11        102602
20   2023-09-10         98819
21   2023-09-09        112074
22   2023-09-08        118872
23   2023-09-07        124672
24   2023-09-06        114028
25   2023-09-05         99637
26   2023-09-04         69628
27   2023-09-03         75978
28   2023-09-02         79976
29   2023-09-01         84290
30   2023-08-31         88556
31   2023-08-30         89517
32   2023-08-29         91314
33   2023-08-28         76220
34   2023-08-27         78205
35   2023-08-26         87758
36   2023-08-25         86367
37   2023-08-24         92572
38   2023-08-23         89831
39   2023-08-22         84554
40   2023-08-21         77676
41   2023-08-20         75288
42   2023-08-19         86711
43   2023-08-18         87110
44   2023-08-17         97296
45   2023-08-16         96950
46   2023-08-15         90854
47   2023-08-14         81376
48   2023-08-13         77061
49   2023-08-12         87146

In [40]:
query_count = """
WITH CTE_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2022/yellow_taxi/yellow_tripdata_*.parquet'
), CTE_count_trip AS (
    SELECT
        DATE(pick_up_time) AS pick_up_date
    FROM CTE_2023
)

SELECT 
    COUNT(*)
FROM CTE_count_trip
WHERE pick_up_date >= '2009-01-01' AND pick_up_date < '2023-10-01'
"""

con = duckdb.connect()
df = con.execute(query_count).fetchdf()
df.head()

   count_star()
0      39655608