In [1]:
import polars as pl
import duckdb

In [2]:
yellow_2023 = pl.read_parquet(r"C:\Users\ekadw\Documents\DATA\NY_Taxi\2023\yellow_taxi\yellow_tripdata_2023-01.parquet")
yellow_2023.head()

shape: (5, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 1.0       ┆ … ┆ 1.0       ┆ 14.3      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:32:10  ┆ 00:40:36  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 1.0       ┆ … ┆ 1.0       ┆ 16.9      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:55:08  ┆ 01:01:27  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 1.0       ┆ … ┆ 1.0       ┆ 34.9      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:25:04  ┆ 00:37:49  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 0.0       ┆ … ┆ 1.0       ┆ 20.85     ┆ 0.0       ┆ 1.25      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:03:48  ┆ 00:13:25  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 1.0       ┆ … ┆ 1.0       ┆ 19.68     ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:10:29  ┆ 00:21:19  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
query = """
WITH CTE_jan_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2023/yellow_taxi/yellow_tripdata_2023-01.parquet'
)

SELECT 
    *
FROM CTE_jan_2023
"""

con = duckdb.connect()
df = con.execute(query).fetchdf()
df.head()

,pick_up_time,drop_off_time,passenger_count,trip_distance,payment_type,total_amount,tip_amount
0,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,2,14.30,0.00
1,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1,16.90,4.00
2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1,34.90,15.00
3,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1,20.85,0.00
4,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1,19.68,3.28

In [ ]:
query_count = """
WITH CTE_jan_2023 AS (
    SELECT 
        tpep_pickup_datetime AS pick_up_time,
        tpep_dropoff_datetime AS drop_off_time,
        passenger_count,
        trip_distance,
        payment_type,
        total_amount,
        tip_amount
    FROM 'C:/Users/ekadw/Documents/DATA/NY_Taxi/2023/yellow_taxi/yellow_tripdata_2023-01.parquet'
)

SELECT 
    *
FROM CTE_jan_2023
"""

con = duckdb.connect()
df = con.execute(query_count).fetchdf()
df.head()