In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\ekadw\Documents\DATA\Stock_Market\symbols_valid_meta.csv")
data.head()

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAAU,Perth Mint Physical Gold ETF,P,,Y,100.0,N,NaN,AAAU,AAAU,N
3,Y,AACG,ATA Creativity Global - American Depositary Sh...,Q,G,N,100.0,N,N,NaN,AACG,N
4,Y,AADR,AdvisorShares Dorsey Wright ADR ETF,P,,Y,100.0,N,NaN,AADR,AADR,N

In [8]:
data[data["Symbol"]=="PRN"]

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
5738,Y,PRN,Invesco DWA Industrials Momentum ETF,Q,G,Y,100.0,N,N,NaN,PRN,N

In [4]:
len(data)

8049

In [3]:
data_etfs = pd.read_csv(r"C:\Users\ekadw\Documents\DATA\Stock_Market\etfs\_PRN.csv")
data_etfs.head()

         Date       Open       High        Low      Close  Adj Close  Volume
0  2006-10-12  25.459999  25.680000  25.459999  25.680000  23.301548   16300
1  2006-10-13  25.680000  25.680000  25.680000  25.680000  23.301548       0
2  2006-10-16  25.879999  26.379999  25.879999  26.379999  23.936714   12900
3  2006-10-17  26.150000  26.240000  26.090000  26.240000  23.809679    2400
4  2006-10-18  26.400000  26.400000  25.990000  25.990000  23.582838     700

In [5]:
len(data_etfs)

3390

In [6]:
data_etfs.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
3385,2020-03-26,54.099998,56.790001,54.099998,56.720001,56.720001,9100
3386,2020-03-27,54.360001,55.900002,54.360001,54.889999,54.889999,8400
3387,2020-03-30,55.509998,56.529999,55.509998,56.529999,56.529999,11700
3388,2020-03-31,55.759998,56.610001,55.490002,55.660000,55.660000,5400
3389,2020-04-01,52.919998,53.259998,52.330002,52.430000,52.430000,2900

In [11]:
data_stocks = pd.read_csv(r"C:\Users\ekadw\Documents\DATA\Stock_Market\stocks\AAON.csv")
data_stocks.head()

         Date      Open      High       Low     Close  Adj Close  Volume
0  1992-12-16  0.099763  0.099763  0.099763  0.099763   0.084743    1900
1  1992-12-17  0.119716  0.129692  0.099763  0.119716   0.101691  163900
2  1992-12-18  0.119716  0.119716  0.119716  0.119716   0.101691   14100
3  1992-12-21  0.099763  0.099763  0.089787  0.099763   0.084743   32400
4  1992-12-22  0.099763  0.119716  0.099763  0.119716   0.101691   62100